name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx myst_parser sphinx_design sphinx-book-theme myst_nb sphinx-markdown-tables sphinx-autobuild sphinx-http-domain sphinx-js sphinxcontrib-bibtex sphinx-copybutton sphinx-thebe sphinxcontrib-blockdiag sphinx-togglebutton sphinxcontrib-mermaid sphinx-panels sphinx-subfigure linkify-it-py
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
